"""initial_schema

Revision ID: 4d3592fe4005
Revises: 
Create Date: 2026-04-02 07:02:12.660047+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d3592fe4005'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=36), nullable=False, comment='UUID v4 agent identifier.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable display name.'),
    sa.Column('agent_type', sa.String(length=10), nullable=False, comment='Kind of participant.'),
    sa.Column('status', sa.String(length=15), nullable=False, comment='Current operational status.'),
    sa.Column('current_task_id', sa.String(length=36), nullable=True, comment='Task currently being executed.'),
    sa.Column('workspace_id', sa.String(length=36), nullable=True, comment='Current workspace ID.'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Contact email (primarily for human agents).'),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('kafka_group_id', sa.String(length=255), nullable=True, comment='Kafka consumer group ID for this agent.'),
    sa.Column('max_concurrent_tasks', sa.SmallInteger(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Arbitrary key/value metadata.'),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deregistered_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("agent_type IN ('human','ai','build','deploy','system')", name=op.f('ck_agents_ck_agents_agent_type')),
    sa.CheckConstraint("status IN ('offline','online','idle','busy','maintenance','deregistered')", name=op.f('ck_agents_ck_agents_status')),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_agents')),
    sa.UniqueConstraint('email', name=op.f('uq_agents_email'))
    )
    op.create_index('ix_agents_agent_type', 'agents', ['agent_type'], unique=False)
    op.create_index('ix_agents_email', 'agents', ['email'], unique=False)
    op.create_index('ix_agents_registered_at', 'agents', ['registered_at'], unique=False)
    op.create_index('ix_agents_status', 'agents', ['status'], unique=False)
    op.create_table('event_records',
    sa.Column('event_id', sa.String(length=36), nullable=False, comment='UUID v4 event identifier.'),
    sa.Column('event_type', sa.String(length=60), nullable=False, comment='Discriminator string identifying the event kind.'),
    sa.Column('topic', sa.String(length=100), nullable=False, comment='Kafka topic this event belongs to.'),
    sa.Column('source', sa.String(length=30), nullable=False, comment='Component that produced this event.'),
    sa.Column('workflow_id', sa.String(length=36), nullable=True, comment='Workflow this event is scoped to.'),
    sa.Column('task_id', sa.String(length=36), nullable=True, comment='Task this event is scoped to.'),
    sa.Column('agent_id', sa.String(length=36), nullable=True, comment='Agent this event is scoped to.'),
    sa.Column('correlation_id', sa.String(length=36), nullable=True, comment='ID linking related events.'),
    sa.Column('causation_id', sa.String(length=36), nullable=True, comment='ID of the event that caused this one.'),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Event-type-specific data.'),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Arbitrary key/value metadata.'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when the event was generated.'),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.CheckConstraint("severity IN ('debug','info','warning','error','critical')", name=op.f('ck_event_records_ck_event_records_severity')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_event_records'))
    )
    op.create_index('ix_event_records_agent_id', 'event_records', ['agent_id'], unique=False)
    op.create_index('ix_event_records_correlation_id', 'event_records', ['correlation_id'], unique=False)
    op.create_index('ix_event_records_event_type', 'event_records', ['event_type'], unique=False)
    op.create_index('ix_event_records_occurred_at', 'event_records', ['occurred_at'], unique=False)
    op.create_index('ix_event_records_source', 'event_records', ['source'], unique=False)
    op.create_index('ix_event_records_task_id', 'event_records', ['task_id'], unique=False)
    op.create_index('ix_event_records_topic', 'event_records', ['topic'], unique=False)
    op.create_index('ix_event_records_workflow_id', 'event_records', ['workflow_id'], unique=False)
    op.create_index('ix_event_records_workflow_occurred', 'event_records', ['workflow_id', 'occurred_at'], unique=False)
    op.create_table('agent_capabilities',
    sa.Column('capability_id', sa.String(length=36), nullable=False, comment='UUID v4 capability identifier.'),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Capability identifier.'),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_capabilities_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capability_id', name=op.f('pk_agent_capabilities')),
    sa.UniqueConstraint('agent_id', 'name', name='uq_agent_capabilities_agent_id')
    )
    op.create_index('ix_agent_capabilities_agent_id', 'agent_capabilities', ['agent_id'], unique=False)
    op.create_index('ix_agent_capabilities_enabled', 'agent_capabilities', ['enabled'], unique=False)
    op.create_index('ix_agent_capabilities_name', 'agent_capabilities', ['name'], unique=False)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.String(length=36), nullable=False, comment='UUID v4 workflow instance identifier.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable workflow name.'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Current lifecycle state.'),
    sa.Column('trigger', sa.String(length=20), nullable=False, comment='How this workflow was initiated.'),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Parsed workflow definition (YAML DSL as JSON).'),
    sa.Column('temporal_run_id', sa.String(length=255), nullable=True, comment='Temporal workflow run ID.'),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=True, comment='Temporal workflow ID (stable across retries).'),
    sa.Column('owner_agent_id', sa.String(length=36), nullable=True, comment='Agent that owns/initiated this workflow.'),
    sa.Column('project', sa.String(length=255), nullable=True, comment='Project/namespace this workflow belongs to.'),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Runtime input parameters.'),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Collected output parameters.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Human-readable error description.'),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Structured error details.'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Arbitrary tags.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when this workflow was created.'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when execution began.'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when execution finished.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of the last state change.'),
    sa.CheckConstraint("status IN ('pending','running','paused','completed','failed','cancelled')", name=op.f('ck_workflows_ck_workflows_status')),
    sa.CheckConstraint("trigger IN ('manual','scheduled','webhook','event','api','retry')", name=op.f('ck_workflows_ck_workflows_trigger')),
    sa.ForeignKeyConstraint(['owner_agent_id'], ['agents.agent_id'], name=op.f('fk_workflows_owner_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('workflow_id', name=op.f('pk_workflows'))
    )
    op.create_index('ix_workflows_created_at', 'workflows', ['created_at'], unique=False)
    op.create_index('ix_workflows_owner_agent_id', 'workflows', ['owner_agent_id'], unique=False)
    op.create_index('ix_workflows_project', 'workflows', ['project'], unique=False)
    op.create_index('ix_workflows_status', 'workflows', ['status'], unique=False)
    op.create_index('ix_workflows_updated_at', 'workflows', ['updated_at'], unique=False)
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.String(length=36), nullable=False, comment='UUID v4 workspace identifier.'),
    sa.Column('agent_id', sa.String(length=36), nullable=False, comment='Agent that owns this workspace.'),
    sa.Column('task_id', sa.String(length=36), nullable=True, comment='Task currently being executed in this workspace.'),
    sa.Column('workflow_id', sa.String(length=36), nullable=True, comment='Workflow this workspace is associated with.'),
    sa.Column('workspace_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('root_path', sa.String(length=2048), nullable=False, comment='Absolute filesystem path to the workspace root.'),
    sa.Column('git_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Current Git state (branch, commit SHA, dirty flag, etc.).'),
    sa.Column('snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Point-in-time workspace snapshots.'),
    sa.Column('repo_url', sa.String(length=2048), nullable=True, comment='Remote Git repository URL.'),
    sa.Column('branch_prefix', sa.String(length=100), nullable=False),
    sa.Column('disk_usage_mb', sa.Float(), nullable=False),
    sa.Column('max_disk_mb', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workspace_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('creating','ready','active','syncing','idle','archived','error')", name=op.f('ck_workspaces_ck_workspaces_status')),
    sa.CheckConstraint("workspace_type IN ('local','remote','ephemeral','shared')", name=op.f('ck_workspaces_ck_workspaces_workspace_type')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_workspaces_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_workspaces'))
    )
    op.create_index('ix_workspaces_agent_id', 'workspaces', ['agent_id'], unique=False)
    op.create_index('ix_workspaces_created_at', 'workspaces', ['created_at'], unique=False)
    op.create_index('ix_workspaces_status', 'workspaces', ['status'], unique=False)
    op.create_index('ix_workspaces_workspace_type', 'workspaces', ['workspace_type'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False, comment='UUID v4 task identifier.'),
    sa.Column('workflow_id', sa.String(length=36), nullable=False, comment='Workflow this task belongs to.'),
    sa.Column('step_id', sa.String(length=36), nullable=True, comment='Workflow step this task was created from.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable task name.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional detailed description.'),
    sa.Column('task_type', sa.String(length=20), nullable=False, comment='Nature of work.'),
    sa.Column('status', sa.String(length=25), nullable=False, comment='Current lifecycle state.'),
    sa.Column('priority', sa.String(length=10), nullable=False, comment='Scheduling priority.'),
    sa.Column('assigned_agent_id', sa.String(length=36), nullable=True, comment='Agent currently responsible for this task.'),
    sa.Column('previous_agent_id', sa.String(length=36), nullable=True, comment='Agent that previously held this task.'),
    sa.Column('workspace_id', sa.String(length=36), nullable=True, comment='Workspace where this task is being executed.'),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Input parameters as a list of {name, value, ...} objects.'),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Output parameters as a list of {name, value, ...} objects.'),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Task IDs that must complete before this task starts.'),
    sa.Column('timeout_secs', sa.Integer(), nullable=False, comment='Maximum execution time in seconds. 0 = no limit.'),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False, comment='Maximum number of automatic retries.'),
    sa.Column('current_retry', sa.SmallInteger(), nullable=False, comment='Current retry attempt number.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Human-readable error description.'),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Structured error details.'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Arbitrary tags.'),
    sa.Column('task_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Arbitrary key/value metadata.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True, comment='Optional deadline for task completion.'),
    sa.CheckConstraint("priority IN ('low','normal','high','critical')", name=op.f('ck_tasks_ck_tasks_priority')),
    sa.CheckConstraint("status IN ('pending','assigned','accepted','in_progress','checkpointed','handoff_requested','handoff_accepted','revert_requested','reverted','completed','failed','cancelled','skipped')", name=op.f('ck_tasks_ck_tasks_status')),
    sa.CheckConstraint("task_type IN ('human','ai','build','deploy','review','approval','notification','integration','analysis')", name=op.f('ck_tasks_ck_tasks_task_type')),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.agent_id'], name=op.f('fk_tasks_assigned_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_agent_id'], ['agents.agent_id'], name=op.f('fk_tasks_previous_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_tasks_workflow_id_workflows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], name=op.f('fk_tasks_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_assigned_agent_id', 'tasks', ['assigned_agent_id'], unique=False)
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_due_at', 'tasks', ['due_at'], unique=False)
    op.create_index('ix_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_task_type', 'tasks', ['task_type'], unique=False)
    op.create_index('ix_tasks_updated_at', 'tasks', ['updated_at'], unique=False)
    op.create_index('ix_tasks_workflow_id', 'tasks', ['workflow_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('checkpoint_id', sa.String(length=36), nullable=False, comment='UUID v4 checkpoint identifier.'),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Monotonically increasing sequence number within a task.'),
    sa.Column('git_commit_sha', sa.String(length=40), nullable=True, comment='Git commit SHA of this checkpoint.'),
    sa.Column('git_branch', sa.String(length=255), nullable=False),
    sa.Column('git_tag', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False, comment='Human-readable description of this checkpoint.'),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_removed', sa.Integer(), nullable=False),
    sa.Column('s3_archive_key', sa.String(length=2048), nullable=True, comment='S3 key for a full workspace archive.'),
    sa.Column('task_progress', sa.Float(), nullable=True, comment='Estimated task completion percentage (0-100).'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checkpoint_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("checkpoint_type IN ('manual','auto','pre_handoff','pre_revert','milestone','ai_proposal','completion')", name=op.f('ck_checkpoints_ck_checkpoints_checkpoint_type')),
    sa.CheckConstraint("status IN ('creating','committed','verified','reverted','failed')", name=op.f('ck_checkpoints_ck_checkpoints_status')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_checkpoints_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_checkpoints_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_checkpoints_workflow_id_workflows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], name=op.f('fk_checkpoints_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id', name=op.f('pk_checkpoints'))
    )
    op.create_index('ix_checkpoints_agent_id', 'checkpoints', ['agent_id'], unique=False)
    op.create_index('ix_checkpoints_created_at', 'checkpoints', ['created_at'], unique=False)
    op.create_index('ix_checkpoints_git_commit_sha', 'checkpoints', ['git_commit_sha'], unique=False)
    op.create_index('ix_checkpoints_status', 'checkpoints', ['status'], unique=False)
    op.create_index('ix_checkpoints_task_id', 'checkpoints', ['task_id'], unique=False)
    op.create_index('ix_checkpoints_workflow_id', 'checkpoints', ['workflow_id'], unique=False)
    op.create_index('ix_checkpoints_workspace_id', 'checkpoints', ['workspace_id'], unique=False)
    op.create_table('reasoning_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='UUID v4 session identifier.'),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False, comment='The goal/objective for this reasoning session.'),
    sa.Column('final_output', sa.Text(), nullable=True),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured proposal produced by this session.'),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('total_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('langgraph_run_id', sa.String(length=255), nullable=True),
    sa.Column('langsmith_run_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('human_review_reason', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','cancelled','awaiting_human')", name=op.f('ck_reasoning_sessions_ck_reasoning_sessions_status')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_reasoning_sessions_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_reasoning_sessions_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_reasoning_sessions_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_reasoning_sessions'))
    )
    op.create_index('ix_reasoning_sessions_agent_id', 'reasoning_sessions', ['agent_id'], unique=False)
    op.create_index('ix_reasoning_sessions_started_at', 'reasoning_sessions', ['started_at'], unique=False)
    op.create_index('ix_reasoning_sessions_status', 'reasoning_sessions', ['status'], unique=False)
    op.create_index('ix_reasoning_sessions_task_id', 'reasoning_sessions', ['task_id'], unique=False)
    op.create_index('ix_reasoning_sessions_workflow_id', 'reasoning_sessions', ['workflow_id'], unique=False)
    op.create_table('task_attempts',
    sa.Column('attempt_id', sa.String(length=36), nullable=False, comment='UUID v4 attempt identifier.'),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=False, comment='Sequential attempt number (1-based).'),
    sa.Column('agent_id', sa.String(length=36), nullable=False, comment='Agent that executed this attempt.'),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_task_attempts_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_task_attempts_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id', name=op.f('pk_task_attempts')),
    sa.UniqueConstraint('task_id', 'attempt_number', name='uq_task_attempts_task_id')
    )
    op.create_index('ix_task_attempts_agent_id', 'task_attempts', ['agent_id'], unique=False)
    op.create_index('ix_task_attempts_task_id', 'task_attempts', ['task_id'], unique=False)
    op.create_table('checkpoint_files',
    sa.Column('file_id', sa.String(length=36), nullable=False, comment='UUID v4 file record identifier.'),
    sa.Column('checkpoint_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False, comment='Relative path within the workspace.'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='Git status: added, modified, deleted, renamed.'),
    sa.Column('old_path', sa.String(length=2048), nullable=True, comment='Previous path for renamed files.'),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True, comment='SHA-256 checksum of the file content.'),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.checkpoint_id'], name=op.f('fk_checkpoint_files_checkpoint_id_checkpoints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_checkpoint_files'))
    )
    op.create_index('ix_checkpoint_files_checkpoint_id', 'checkpoint_files', ['checkpoint_id'], unique=False)
    op.create_index('ix_checkpoint_files_path', 'checkpoint_files', ['path'], unique=False)
    op.create_table('handoffs',
    sa.Column('handoff_id', sa.String(length=36), nullable=False, comment='UUID v4 handoff identifier.'),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('source_agent_id', sa.String(length=36), nullable=False),
    sa.Column('target_agent_id', sa.String(length=36), nullable=True),
    sa.Column('handoff_type', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=36), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Briefing context for the target agent.'),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('handoff_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("handoff_type IN ('delegation','escalation','completion','review','emergency','scheduled','ai_to_human','human_to_ai')", name=op.f('ck_handoffs_ck_handoffs_handoff_type')),
    sa.CheckConstraint("status IN ('requested','pending_acceptance','accepted','completed','rejected','expired','failed','cancelled')", name=op.f('ck_handoffs_ck_handoffs_status')),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.checkpoint_id'], name=op.f('fk_handoffs_checkpoint_id_checkpoints'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.agent_id'], name=op.f('fk_handoffs_source_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.agent_id'], name=op.f('fk_handoffs_target_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_handoffs_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_handoffs_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('handoff_id', name=op.f('pk_handoffs'))
    )
    op.create_index('ix_handoffs_requested_at', 'handoffs', ['requested_at'], unique=False)
    op.create_index('ix_handoffs_source_agent_id', 'handoffs', ['source_agent_id'], unique=False)
    op.create_index('ix_handoffs_status', 'handoffs', ['status'], unique=False)
    op.create_index('ix_handoffs_target_agent_id', 'handoffs', ['target_agent_id'], unique=False)
    op.create_index('ix_handoffs_task_id', 'handoffs', ['task_id'], unique=False)
    op.create_index('ix_handoffs_workflow_id', 'handoffs', ['workflow_id'], unique=False)
    op.create_table('reasoning_steps',
    sa.Column('step_id', sa.String(length=36), nullable=False, comment='UUID v4 step identifier.'),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('step_type', sa.String(length=15), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Monotonically increasing sequence number within a session.'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('step_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("step_type IN ('thought','tool_call','observation','plan','decision','proposal','reflection','human_input','final_answer','error')", name=op.f('ck_reasoning_steps_ck_reasoning_steps_step_type')),
    sa.ForeignKeyConstraint(['session_id'], ['reasoning_sessions.session_id'], name=op.f('fk_reasoning_steps_session_id_reasoning_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', name=op.f('pk_reasoning_steps'))
    )
    op.create_index('ix_reasoning_steps_sequence', 'reasoning_steps', ['sequence'], unique=False)
    op.create_index('ix_reasoning_steps_session_id', 'reasoning_steps', ['session_id'], unique=False)
    op.create_index('ix_reasoning_steps_step_type', 'reasoning_steps', ['step_type'], unique=False)
    op.create_table('tool_calls',
    sa.Column('tool_call_id', sa.String(length=36), nullable=False, comment='UUID v4 tool call identifier.'),
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['reasoning_steps.step_id'], name=op.f('fk_tool_calls_step_id_reasoning_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_call_id', name=op.f('pk_tool_calls'))
    )
    op.create_index('ix_tool_calls_is_error', 'tool_calls', ['is_error'], unique=False)
    op.create_index('ix_tool_calls_step_id', 'tool_calls', ['step_id'], unique=False)
    op.create_index('ix_tool_calls_tool_name', 'tool_calls', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_calls_tool_name', table_name='tool_calls')
    op.drop_index('ix_tool_calls_step_id', table_name='tool_calls')
    op.drop_index('ix_tool_calls_is_error', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('ix_reasoning_steps_step_type', table_name='reasoning_steps')
    op.drop_index('ix_reasoning_steps_session_id', table_name='reasoning_steps')
    op.drop_index('ix_reasoning_steps_sequence', table_name='reasoning_steps')
    op.drop_table('reasoning_steps')
    op.drop_index('ix_handoffs_workflow_id', table_name='handoffs')
    op.drop_index('ix_handoffs_task_id', table_name='handoffs')
    op.drop_index('ix_handoffs_target_agent_id', table_name='handoffs')
    op.drop_index('ix_handoffs_status', table_name='handoffs')
    op.drop_index('ix_handoffs_source_agent_id', table_name='handoffs')
    op.drop_index('ix_handoffs_requested_at', table_name='handoffs')
    op.drop_table('handoffs')
    op.drop_index('ix_checkpoint_files_path', table_name='checkpoint_files')
    op.drop_index('ix_checkpoint_files_checkpoint_id', table_name='checkpoint_files')
    op.drop_table('checkpoint_files')
    op.drop_index('ix_task_attempts_task_id', table_name='task_attempts')
    op.drop_index('ix_task_attempts_agent_id', table_name='task_attempts')
    op.drop_table('task_attempts')
    op.drop_index('ix_reasoning_sessions_workflow_id', table_name='reasoning_sessions')
    op.drop_index('ix_reasoning_sessions_task_id', table_name='reasoning_sessions')
    op.drop_index('ix_reasoning_sessions_status', table_name='reasoning_sessions')
    op.drop_index('ix_reasoning_sessions_started_at', table_name='reasoning_sessions')
    op.drop_index('ix_reasoning_sessions_agent_id', table_name='reasoning_sessions')
    op.drop_table('reasoning_sessions')
    op.drop_index('ix_checkpoints_workspace_id', table_name='checkpoints')
    op.drop_index('ix_checkpoints_workflow_id', table_name='checkpoints')
    op.drop_index('ix_checkpoints_task_id', table_name='checkpoints')
    op.drop_index('ix_checkpoints_status', table_name='checkpoints')
    op.drop_index('ix_checkpoints_git_commit_sha', table_name='checkpoints')
    op.drop_index('ix_checkpoints_created_at', table_name='checkpoints')
    op.drop_index('ix_checkpoints_agent_id', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index('ix_tasks_workflow_id', table_name='tasks')
    op.drop_index('ix_tasks_updated_at', table_name='tasks')
    op.drop_index('ix_tasks_task_type', table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_priority', table_name='tasks')
    op.drop_index('ix_tasks_due_at', table_name='tasks')
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_index('ix_tasks_assigned_agent_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_workspaces_workspace_type', table_name='workspaces')
    op.drop_index('ix_workspaces_status', table_name='workspaces')
    op.drop_index('ix_workspaces_created_at', table_name='workspaces')
    op.drop_index('ix_workspaces_agent_id', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_workflows_updated_at', table_name='workflows')
    op.drop_index('ix_workflows_status', table_name='workflows')
    op.drop_index('ix_workflows_project', table_name='workflows')
    op.drop_index('ix_workflows_owner_agent_id', table_name='workflows')
    op.drop_index('ix_workflows_created_at', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('ix_agent_capabilities_name', table_name='agent_capabilities')
    op.drop_index('ix_agent_capabilities_enabled', table_name='agent_capabilities')
    op.drop_index('ix_agent_capabilities_agent_id', table_name='agent_capabilities')
    op.drop_table('agent_capabilities')
    op.drop_index('ix_event_records_workflow_occurred', table_name='event_records')
    op.drop_index('ix_event_records_workflow_id', table_name='event_records')
    op.drop_index('ix_event_records_topic', table_name='event_records')
    op.drop_index('ix_event_records_task_id', table_name='event_records')
    op.drop_index('ix_event_records_source', table_name='event_records')
    op.drop_index('ix_event_records_occurred_at', table_name='event_records')
    op.drop_index('ix_event_records_event_type', table_name='event_records')
    op.drop_index('ix_event_records_correlation_id', table_name='event_records')
    op.drop_index('ix_event_records_agent_id', table_name='event_records')
    op.drop_table('event_records')
    op.drop_index('ix_agents_status', table_name='agents')
    op.drop_index('ix_agents_registered_at', table_name='agents')
    op.drop_index('ix_agents_email', table_name='agents')
    op.drop_index('ix_agents_agent_type', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
